/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAnaliseRouteImport } from './routes/_authenticated/analise'
import { Route as AuthenticatedAprovacaoRouteImport } from './routes/_authenticated/aprovacao'
import { Route as AuthenticatedArquivosRouteImport } from './routes/_authenticated/arquivos'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCriacaoRouteImport } from './routes/_authenticated/criacao'
import { Route as AuthenticatedCriarRouteImport } from './routes/_authenticated/criar'
import { Route as AuthenticatedLinkPerfilRouteImport } from './routes/_authenticated/link-perfil'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPermissoesRouteImport } from './routes/_authenticated/permissoes'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as ATokenRouteImport } from './routes/a.$token'
import { Route as BSlugRouteImport } from './routes/b.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnaliseRoute = AuthenticatedAnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAprovacaoRoute = AuthenticatedAprovacaoRouteImport.update({
  id: '/aprovacao',
  path: '/aprovacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArquivosRoute = AuthenticatedArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCriacaoRoute = AuthenticatedCriacaoRouteImport.update({
  id: '/criacao',
  path: '/criacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCriarRoute = AuthenticatedCriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinkPerfilRoute = AuthenticatedLinkPerfilRouteImport.update({
  id: '/link-perfil',
  path: '/link-perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissoesRoute = AuthenticatedPermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ATokenRoute = ATokenRouteImport.update({
  id: '/a/$token',
  path: '/a/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analise': typeof AuthenticatedAnaliseRoute
  '/aprovacao': typeof AuthenticatedAprovacaoRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/criacao': typeof AuthenticatedCriacaoRoute
  '/criar': typeof AuthenticatedCriarRoute
  '/link-perfil': typeof AuthenticatedLinkPerfilRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/a/$token': typeof ATokenRoute
  '/b/$slug': typeof BSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analise': typeof AuthenticatedAnaliseRoute
  '/aprovacao': typeof AuthenticatedAprovacaoRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/criacao': typeof AuthenticatedCriacaoRoute
  '/criar': typeof AuthenticatedCriarRoute
  '/link-perfil': typeof AuthenticatedLinkPerfilRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/a/$token': typeof ATokenRoute
  '/b/$slug': typeof BSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/analise': typeof AuthenticatedAnaliseRoute
  '/_authenticated/aprovacao': typeof AuthenticatedAprovacaoRoute
  '/_authenticated/arquivos': typeof AuthenticatedArquivosRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/criacao': typeof AuthenticatedCriacaoRoute
  '/_authenticated/criar': typeof AuthenticatedCriarRoute
  '/_authenticated/link-perfil': typeof AuthenticatedLinkPerfilRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/permissoes': typeof AuthenticatedPermissoesRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/a/$token': typeof ATokenRoute
  '/b/$slug': typeof BSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analise'
    | '/aprovacao'
    | '/arquivos'
    | '/clientes'
    | '/configuracoes'
    | '/criacao'
    | '/criar'
    | '/link-perfil'
    | '/painel'
    | '/permissoes'
    | '/relatorios'
    | '/a/$token'
    | '/b/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analise'
    | '/aprovacao'
    | '/arquivos'
    | '/clientes'
    | '/configuracoes'
    | '/criacao'
    | '/criar'
    | '/link-perfil'
    | '/painel'
    | '/permissoes'
    | '/relatorios'
    | '/a/$token'
    | '/b/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/analise'
    | '/_authenticated/aprovacao'
    | '/_authenticated/arquivos'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/criacao'
    | '/_authenticated/criar'
    | '/_authenticated/link-perfil'
    | '/_authenticated/painel'
    | '/_authenticated/permissoes'
    | '/_authenticated/relatorios'
    | '/a/$token'
    | '/b/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ATokenRoute: typeof ATokenRoute
  BSlugRoute: typeof BSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analise': {
      id: '/_authenticated/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AuthenticatedAnaliseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aprovacao': {
      id: '/_authenticated/aprovacao'
      path: '/aprovacao'
      fullPath: '/aprovacao'
      preLoaderRoute: typeof AuthenticatedAprovacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arquivos': {
      id: '/_authenticated/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof AuthenticatedArquivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/criacao': {
      id: '/_authenticated/criacao'
      path: '/criacao'
      fullPath: '/criacao'
      preLoaderRoute: typeof AuthenticatedCriacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/criar': {
      id: '/_authenticated/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof AuthenticatedCriarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/link-perfil': {
      id: '/_authenticated/link-perfil'
      path: '/link-perfil'
      fullPath: '/link-perfil'
      preLoaderRoute: typeof AuthenticatedLinkPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissoes': {
      id: '/_authenticated/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof AuthenticatedPermissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/a/$token': {
      id: '/a/$token'
      path: '/a/$token'
      fullPath: '/a/$token'
      preLoaderRoute: typeof ATokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnaliseRoute: typeof AuthenticatedAnaliseRoute
  AuthenticatedAprovacaoRoute: typeof AuthenticatedAprovacaoRoute
  AuthenticatedArquivosRoute: typeof AuthenticatedArquivosRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCriacaoRoute: typeof AuthenticatedCriacaoRoute
  AuthenticatedCriarRoute: typeof AuthenticatedCriarRoute
  AuthenticatedLinkPerfilRoute: typeof AuthenticatedLinkPerfilRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPermissoesRoute: typeof AuthenticatedPermissoesRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnaliseRoute: AuthenticatedAnaliseRoute,
  AuthenticatedAprovacaoRoute: AuthenticatedAprovacaoRoute,
  AuthenticatedArquivosRoute: AuthenticatedArquivosRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCriacaoRoute: AuthenticatedCriacaoRoute,
  AuthenticatedCriarRoute: AuthenticatedCriarRoute,
  AuthenticatedLinkPerfilRoute: AuthenticatedLinkPerfilRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPermissoesRoute: AuthenticatedPermissoesRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ATokenRoute: ATokenRoute,
  BSlugRoute: BSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
